"""add approved_at to users

Revision ID: 357b56649898
Revises: fc77b2bb710f
Created: 2026-08-06 11:32:49.120743
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '357b56649898'
down_revision: str | None = 'fc77b2bb710f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True)
        )

    # Everyone who already had an account predates the approval flow and is,
    # by definition, already let in. Without this backfill they would all read
    # as "waiting for approval" and nobody could sign in — including the
    # administrator who runs this migration.
    op.execute("UPDATE users SET approved_at = created_at WHERE approved_at IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
